DROP TABLE IF EXISTS EMPLOYEE_INFO;

CREATE TABLE EMPLOYEE_INFO (
   ID VARCHAR(36),
   NAME VARCHAR(200),
   EMAIL_ID VARCHAR(400),
   MOBILE_NUMBER VARCHAR(14),
   FATHER_NAME VARCHAR(200),
   MOTHER_NAME VARCHAR(200),
   AGE INT,
   DATE_OF_BIRTH TIMESTAMP,
   CURRENT_CTC FLOAT(4),
   EXPECTED_CTC FLOAT(4),
   DESIGNATION VARCHAR(400),
   ORGANIZATION_TYPE VARCHAR(400),
   CURRENT_ORGANIZATION_NAME VARCHAR(400),
   CURRENT_LOCATION VARCHAR(400),
   JOB_PROFILE VARCHAR(400),
   RESUME_LOCATION VARCHAR(1000),
   CREATE_TIME TIMESTAMP,
   UPDATE_TIME TIMESTAMP,
   CONSTRAINT EMPLOYEE_INFO_PK PRIMARY KEY(ID)
);